#!/usr/bin/env python3
"""Patch the LOCAL build source so a rebuild keeps the cross-reference fix.

The fix itself lives in two places:
  * app.py     -- GET /api/xrefs ordering + POST /api/xrefs edit-in-place  (patched directly)
  * index.html -- saveXref()                                              (GENERATED by build_bible.py)

Because index.html is generated, the saveXref change has to be made in build_bible.py
or the next `bash src/build.sh` will silently undo it. Run this once:

    python local-build-patches/patch_xref_order.py [path/to/build_bible.py]

Idempotent: re-running after a successful patch reports "already patched".
"""
import sys, os

OLD_DELETE = (
    "if(XR_EDIT){var oldid=XR_EDIT.id;try{await api('DELETE','/api/xrefs',{id:oldid});}"
    "catch(e){}if(XC[k])Object.keys(XC[k]).forEach(function(v){XC[k][v]="
    "XC[k][v].filter(function(x){return x.id!==oldid;});});}"
)
NEW_DELETE = (
    "var editId=XR_EDIT?XR_EDIT.id:null;  "
    "// EDIT IN PLACE: no DELETE first, so the row keeps its id AND its slot in the list"
)

OLD_POST = (
    "var d2=await api('POST','/api/xrefs',{book:XREF_SRC.book,chapter:XREF_SRC.chap,"
    "verse:XREF_SRC.verse,tbook:tbook,tchapter:tchap,tverse:tverse,tverse_end:tvend,note:note});"
    "XC[k]=XC[k]||{};var arr=(XC[k][XREF_SRC.verse]||[]).filter(function(x){return x.id!==d2.id;});"
    "arr.push({id:d2.id,tbook:d2.tbook,tchapter:d2.tchapter,tverse:d2.tverse,"
    "tverse_end:d2.tverse_end,ref:d2.ref,note:d2.note});XC[k][XREF_SRC.verse]=arr;"
)
NEW_POST = (
    "var d2=await api('POST','/api/xrefs',{id:editId,book:XREF_SRC.book,chapter:XREF_SRC.chap,"
    "verse:XREF_SRC.verse,tbook:tbook,tchapter:tchap,tverse:tverse,tverse_end:tvend,note:note});"
    "XC[k]=XC[k]||{};var arr=(XC[k][XREF_SRC.verse]||[]).slice();"
    "var item={id:d2.id,tbook:d2.tbook,tchapter:d2.tchapter,tverse:d2.tverse,"
    "tverse_end:d2.tverse_end,ref:d2.ref,note:d2.note};var at=-1;"
    "for(var i=0;i<arr.length;i++){if(arr[i].id===d2.id){at=i;break;}}"
    "if(at>=0){arr[at]=item;}else{arr.push(item);}XC[k][XREF_SRC.verse]=arr;"
)

path = sys.argv[1] if len(sys.argv) > 1 else "src/build_bible.py"
if not os.path.exists(path):
    sys.exit("Can't find %s -- pass the path to build_bible.py as an argument." % path)

src = open(path, encoding="utf-8").read()
if NEW_POST in src:
    print("already patched: %s" % path)
    sys.exit(0)

missing = [n for n, s in (("DELETE-then-POST edit block", OLD_DELETE),
                          ("POST + XC update", OLD_POST)) if s not in src]
if missing:
    sys.exit("Could not find: %s.\nbuild_bible.py has drifted -- patch saveXref() by hand "
             "(compare against the patched index.html)." % ", ".join(missing))

src = src.replace(OLD_DELETE, NEW_DELETE).replace(OLD_POST, NEW_POST)
open(path + ".bak", "w", encoding="utf-8").write(open(path, encoding="utf-8").read())
open(path, "w", encoding="utf-8").write(src)
print("patched %s  (backup: %s.bak)" % (path, path))
print("Now rebuild: bash src/build.sh")
